
name: Testing

on: [push, pull_request]

jobs:
  calc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Creating build/
      run: mkdir build/
    - name: Installing dependencies
      run: sudo apt-get install libsfml-dev
    - name: Compile
      working-directory: build/
      run: |
        which libsfml-dev
        cmake ..
        make
    - name: Run Tests
      working-directory: build/
      run: ctest -V